/**
 * @packageDocumentation
 * @module api.functional.v1.category
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IResponse } from "../../../../../src/shared/types/response";
import type { CreateCategoryDto } from "../../../../../src/v1/category/category.dto";
import type {
  ICategoryWithRelations,
  ICategory,
} from "../../../../../src/v1/category/category.interface";

/**
 * @controller CategoryController.getAllCategories
 * @path GET /v1/category
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllCategories(
  connection: IConnection,
): Promise<getAllCategories.Output> {
  return !!connection.simulate
    ? getAllCategories.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getAllCategories.METADATA,
        template: getAllCategories.METADATA.path,
        path: getAllCategories.path(),
      });
}
export namespace getAllCategories {
  export type Output = Primitive<IResponse<Array<ICategoryWithRelations>>>;

  export const METADATA = {
    method: "GET",
    path: "/v1/category",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/v1/category";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IResponse<Array<ICategoryWithRelations>>>> =>
    typia.random<Primitive<IResponse<Array<ICategoryWithRelations>>>>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * @controller CategoryController.createCategory
 * @path POST /v1/category
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createCategory(
  connection: IConnection,
  body: createCategory.Input,
): Promise<createCategory.Output> {
  return !!connection.simulate
    ? createCategory.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createCategory.METADATA,
          template: createCategory.METADATA.path,
          path: createCategory.path(),
        },
        body,
      );
}
export namespace createCategory {
  export type Input = Primitive<CreateCategoryDto>;
  export type Output = Primitive<IResponse<ICategory>>;

  export const METADATA = {
    method: "POST",
    path: "/v1/category",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/v1/category";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IResponse<ICategory>>> =>
    typia.random<Primitive<IResponse<ICategory>>>(g);
  export const simulate = (
    connection: IConnection,
    body: createCategory.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
