/**
 * @packageDocumentation
 * @module api.functional.v1.auth.role
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IConnection,
  Primitive,
  IPropagation,
  Resolved,
  HttpError,
} from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { TypeGuardError } from "typia/lib/TypeGuardError";

import type { ExcludePassword } from "../../../../../shared/types/omit-password";
import type { IErrorResponse } from "../../../../../shared/types/response";
import type { UpdateUserRoleDto } from "../../../../../v1/auth/auth.dto";
import type { UserDto } from "../../../../../v1/user/user.dto";

/**
 * @throws 400 invalid request
 * @throws 404 user not found
 * @controller AuthController.updateUserRole
 * @path PATCH /v1/auth/role
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateUserRole(
  connection: IConnection,
  body: updateUserRole.Input,
): Promise<updateUserRole.Output> {
  typia.assert<typeof body>(body);
  return !!connection.simulate
    ? updateUserRole.simulate(connection, body)
    : PlainFetcher.propagate(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...updateUserRole.METADATA,
          template: updateUserRole.METADATA.path,
          path: updateUserRole.path(),
        },
        body,
      );
}
export namespace updateUserRole {
  export type Input = Primitive<UpdateUserRoleDto>;
  export type Output = IPropagation<{
    200: ExcludePassword<UserDto>;
    400: TypeGuardError<any>;
    404: IErrorResponse<404>;
  }>;

  export const METADATA = {
    method: "PATCH",
    path: "/v1/auth/role",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/v1/auth/role";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<ExcludePassword<UserDto>>> =>
    typia.random<Primitive<ExcludePassword<UserDto>>>(g);
  export const simulate = (
    connection: IConnection,
    body: updateUserRole.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    };
  };
}
