/**
 * @packageDocumentation
 * @module api.functional.v1.product
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as course from "./course";
