/**
 * @packageDocumentation
 * @module api.functional.v1.auth.verify
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IResponse } from "../../../../../../src/shared/types/response";
import type { VerifyTokenDto } from "../../../../../../src/v1/auth/auth.dto";
import type { IAccessTokenPayload } from "../../../../../../src/v1/auth/auth.interface";

/**
 * @controller AuthController.verifyAccessToken
 * @path POST /v1/auth/verify
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function verifyAccessToken(
  connection: IConnection,
  body: verifyAccessToken.Input,
): Promise<verifyAccessToken.Output> {
  return !!connection.simulate
    ? verifyAccessToken.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...verifyAccessToken.METADATA,
          template: verifyAccessToken.METADATA.path,
          path: verifyAccessToken.path(),
        },
        body,
      );
}
export namespace verifyAccessToken {
  export type Input = Primitive<VerifyTokenDto>;
  export type Output = Primitive<IResponse<IAccessTokenPayload>>;

  export const METADATA = {
    method: "POST",
    path: "/v1/auth/verify",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/v1/auth/verify";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IResponse<IAccessTokenPayload>>> =>
    typia.random<Primitive<IResponse<IAccessTokenPayload>>>(g);
  export const simulate = (
    connection: IConnection,
    body: verifyAccessToken.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
