/**
 * @packageDocumentation
 * @module api.functional.v1.ui.component.repeat_timer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IConnection,
  IPropagation,
  Primitive,
  Resolved,
  HttpError,
} from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { Uuid } from "../../../../../../shared/types/primitive";
import type {
  UiRepeatTimerDto,
  CreateUiRepeatTimerDto,
  DeletedUiRepeatTimerDto,
} from "../../../../../../v1/ui/component/repeat-timer/ui-repeat-timer.dto";

/**
 * @controller UiRepeatTimerController.getUiRepeatTimer
 * @path GET /v1/ui/component/repeat-timer/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUiRepeatTimer(
  connection: IConnection,
  id: Uuid,
): Promise<getUiRepeatTimer.Output> {
  typia.assert<typeof id>(id);
  return !!connection.simulate
    ? getUiRepeatTimer.simulate(connection, id)
    : PlainFetcher.propagate(connection, {
        ...getUiRepeatTimer.METADATA,
        template: getUiRepeatTimer.METADATA.path,
        path: getUiRepeatTimer.path(id),
      });
}
export namespace getUiRepeatTimer {
  export type Output = IPropagation<{
    200: null | UiRepeatTimerDto;
  }>;

  export const METADATA = {
    method: "GET",
    path: "/v1/ui/component/repeat-timer/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: Uuid) =>
    `/v1/ui/component/repeat-timer/${encodeURIComponent(id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<null | UiRepeatTimerDto>> =>
    typia.random<Primitive<null | UiRepeatTimerDto>>(g);
  export const simulate = (connection: IConnection, id: Uuid): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    };
  };
}

/**
 * @controller UiRepeatTimerController.createUiRepeatTimer
 * @path POST /v1/ui/component/repeat-timer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createUiRepeatTimer(
  connection: IConnection,
  body: createUiRepeatTimer.Input,
): Promise<createUiRepeatTimer.Output> {
  typia.assert<typeof body>(body);
  return !!connection.simulate
    ? createUiRepeatTimer.simulate(connection, body)
    : PlainFetcher.propagate(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createUiRepeatTimer.METADATA,
          template: createUiRepeatTimer.METADATA.path,
          path: createUiRepeatTimer.path(),
        },
        body,
      );
}
export namespace createUiRepeatTimer {
  export type Input = Primitive<CreateUiRepeatTimerDto>;
  export type Output = IPropagation<{
    201: UiRepeatTimerDto;
  }>;

  export const METADATA = {
    method: "POST",
    path: "/v1/ui/component/repeat-timer",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/v1/ui/component/repeat-timer";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<UiRepeatTimerDto>> =>
    typia.random<Primitive<UiRepeatTimerDto>>(g);
  export const simulate = (
    connection: IConnection,
    body: createUiRepeatTimer.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 201,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    };
  };
}

/**
 * @controller UiRepeatTimerController.updateUiRepeatTimer
 * @path PATCH /v1/ui/component/repeat-timer/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateUiRepeatTimer(
  connection: IConnection,
  id: Uuid,
  body: updateUiRepeatTimer.Input,
): Promise<updateUiRepeatTimer.Output> {
  typia.assert<typeof id>(id);
  typia.assert<typeof body>(body);
  return !!connection.simulate
    ? updateUiRepeatTimer.simulate(connection, id, body)
    : PlainFetcher.propagate(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...updateUiRepeatTimer.METADATA,
          template: updateUiRepeatTimer.METADATA.path,
          path: updateUiRepeatTimer.path(id),
        },
        body,
      );
}
export namespace updateUiRepeatTimer {
  export type Input = Primitive<Partial<UiRepeatTimerDto>>;
  export type Output = IPropagation<{
    200: UiRepeatTimerDto;
  }>;

  export const METADATA = {
    method: "PATCH",
    path: "/v1/ui/component/repeat-timer/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: Uuid) =>
    `/v1/ui/component/repeat-timer/${encodeURIComponent(id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<UiRepeatTimerDto>> =>
    typia.random<Primitive<UiRepeatTimerDto>>(g);
  export const simulate = (
    connection: IConnection,
    id: Uuid,
    body: updateUiRepeatTimer.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(id));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    };
  };
}

/**
 * @controller UiRepeatTimerController.deleteUiRepeatTimer
 * @path DELETE /v1/ui/component/repeat-timer/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteUiRepeatTimer(
  connection: IConnection,
  id: Uuid,
): Promise<deleteUiRepeatTimer.Output> {
  typia.assert<typeof id>(id);
  return !!connection.simulate
    ? deleteUiRepeatTimer.simulate(connection, id)
    : PlainFetcher.propagate(connection, {
        ...deleteUiRepeatTimer.METADATA,
        template: deleteUiRepeatTimer.METADATA.path,
        path: deleteUiRepeatTimer.path(id),
      });
}
export namespace deleteUiRepeatTimer {
  export type Output = IPropagation<{
    200: DeletedUiRepeatTimerDto;
  }>;

  export const METADATA = {
    method: "DELETE",
    path: "/v1/ui/component/repeat-timer/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: Uuid) =>
    `/v1/ui/component/repeat-timer/${encodeURIComponent(id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<DeletedUiRepeatTimerDto>> =>
    typia.random<Primitive<DeletedUiRepeatTimerDto>>(g);
  export const simulate = (connection: IConnection, id: Uuid): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    };
  };
}
