/**
 * @packageDocumentation
 * @module api.functional.v1.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IResponse } from "../../../../../src/shared/types/response";
import type {
  LoginUserDto,
  SignupUserDto,
} from "../../../../../src/v1/auth/auth.dto";
import type { IAuthTokens } from "../../../../../src/v1/auth/auth.interface";
import type { IUserWithoutPassword } from "../../../../../src/v1/user/user.interface";

export * as verify from "./verify";
export * as refresh_token from "./refresh_token";

/**
 * @controller AuthController.login
 * @path POST /v1/auth/login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  body: login.Input,
): Promise<login.Output> {
  return !!connection.simulate
    ? login.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...login.METADATA,
          template: login.METADATA.path,
          path: login.path(),
        },
        body,
      );
}
export namespace login {
  export type Input = Primitive<LoginUserDto>;
  export type Output = Primitive<IResponse<IAuthTokens>>;

  export const METADATA = {
    method: "POST",
    path: "/v1/auth/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/v1/auth/login";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IResponse<IAuthTokens>>> =>
    typia.random<Primitive<IResponse<IAuthTokens>>>(g);
  export const simulate = (
    connection: IConnection,
    body: login.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * @controller AuthController.signup
 * @path POST /v1/auth/signup
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function signup(
  connection: IConnection,
  body: signup.Input,
): Promise<signup.Output> {
  return !!connection.simulate
    ? signup.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...signup.METADATA,
          template: signup.METADATA.path,
          path: signup.path(),
        },
        body,
      );
}
export namespace signup {
  export type Input = Primitive<SignupUserDto>;
  export type Output = Primitive<IResponse<IUserWithoutPassword>>;

  export const METADATA = {
    method: "POST",
    path: "/v1/auth/signup",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/v1/auth/signup";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IResponse<IUserWithoutPassword>>> =>
    typia.random<Primitive<IResponse<IUserWithoutPassword>>>(g);
  export const simulate = (
    connection: IConnection,
    body: signup.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
