/**
 * @packageDocumentation
 * @module api.functional.v1.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IConnection,
  Resolved,
  IPropagation,
  Primitive,
  HttpError,
} from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { PaginationDto } from "../../../../core/pagination.dto";
import type { ExcludePassword } from "../../../../shared/types/omit-password";
import type { Uuid } from "../../../../shared/types/primitive";
import type { UserDto } from "../../../../v1/user/user.dto";

/**
 * @controller UserController.getUsers
 * @path GET /v1/user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUsers(
  connection: IConnection,
  query: getUsers.Query,
): Promise<getUsers.Output> {
  typia.assert<typeof query>(query);
  return !!connection.simulate
    ? getUsers.simulate(connection, query)
    : PlainFetcher.propagate(connection, {
        ...getUsers.METADATA,
        template: getUsers.METADATA.path,
        path: getUsers.path(query),
      });
}
export namespace getUsers {
  export type Query = Resolved<PaginationDto>;
  export type Output = IPropagation<{
    200: Array<ExcludePassword<UserDto>>;
  }>;

  export const METADATA = {
    method: "GET",
    path: "/v1/user",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (query: getUsers.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/v1/user";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<Array<ExcludePassword<UserDto>>>> =>
    typia.random<Primitive<Array<ExcludePassword<UserDto>>>>(g);
  export const simulate = (
    connection: IConnection,
    query: getUsers.Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(query),
      contentType: "application/json",
    });
    try {
      assert.query(() => typia.assert(query));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    };
  };
}

/**
 * @controller UserController.getUser
 * @path GET /v1/user/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUser(
  connection: IConnection,
  id: Uuid,
): Promise<getUser.Output> {
  typia.assert<typeof id>(id);
  return !!connection.simulate
    ? getUser.simulate(connection, id)
    : PlainFetcher.propagate(connection, {
        ...getUser.METADATA,
        template: getUser.METADATA.path,
        path: getUser.path(id),
      });
}
export namespace getUser {
  export type Output = IPropagation<{
    200: null | ExcludePassword<UserDto>;
  }>;

  export const METADATA = {
    method: "GET",
    path: "/v1/user/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: Uuid) =>
    `/v1/user/${encodeURIComponent(id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<null | ExcludePassword<UserDto>>> =>
    typia.random<Primitive<null | ExcludePassword<UserDto>>>(g);
  export const simulate = (connection: IConnection, id: Uuid): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    };
  };
}
